-- A ordem de publicação e a contagem que mata a linha. A tabela da outbox já
-- existe; esta migration acrescenta duas colunas e troca o índice da varredura.
-- Nenhuma das três tabelas financeiras é tocada.
--
-- Todo comando é reaplicável: a migration roda como Job antes das réplicas, e
-- uma segunda aplicação contra um banco já migrado termina sem erro.

-- `created_at` é o instante em que o evento aconteceu, lido do relógio do
-- processo antes de a carteira ser travada. Duas operações da mesma carteira
-- podem commitar na ordem inversa dos seus instantes — o lock serializa o
-- commit, não a leitura do relógio que veio antes dele —, e uma varredura
-- ordenada por `created_at` publicaria a segunda primeiro: o consumidor
-- receberia a versão 3 da carteira antes da 2.
--
-- A sequência é atribuída no INSERT, que acontece sob o lock daquela carteira,
-- então ela é a ordem do commit. É o que o ledger já faz com `sequence_number`,
-- e o que `go-reads` crava: `created_at` sozinho não ordena.
ALTER TABLE outbox_events
    ADD COLUMN IF NOT EXISTS publish_seq bigint GENERATED BY DEFAULT AS IDENTITY;

-- O índice da varredura passa a servir a nova ordem. O antigo, por
-- `(wallet_id, created_at, event_id)`, não serve mais a nenhuma consulta.
DROP INDEX IF EXISTS outbox_events_publish_queue;

CREATE INDEX IF NOT EXISTS outbox_events_publish_queue
    ON outbox_events (wallet_id, publish_seq)
    WHERE published_at IS NULL AND dead_at IS NULL;

-- A ordem de publicação é tão imutável quanto o payload: reescrevê-la seria
-- reordenar eventos que um consumidor já pode ter recebido.
CREATE OR REPLACE FUNCTION outbox_events_refuse_payload_change() RETURNS trigger
    LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.event_id    IS DISTINCT FROM OLD.event_id
    OR NEW.event_type  IS DISTINCT FROM OLD.event_type
    OR NEW.wallet_id   IS DISTINCT FROM OLD.wallet_id
    OR NEW.payload     IS DISTINCT FROM OLD.payload
    OR NEW.created_at  IS DISTINCT FROM OLD.created_at
    OR NEW.publish_seq IS DISTINCT FROM OLD.publish_seq THEN
        RAISE EXCEPTION 'outbox_events payload is immutable'
            USING ERRCODE = 'restrict_violation';
    END IF;
    RETURN NEW;
END;
$$;
